language: java
os: osx
before_install:
  - brew cask install java
  - git config --global user.email "travis-ci@destroystokyo.com"
  - git config --global user.name "Travis CI"
  - ./paper patch
after_success:
  - ./scripts/paperclip.sh "."
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work'
