name: Performance problem
about: Report performance problems or areas of concern
body:
  - type: markdown
    attributes:
      value: |
        Before reporting performance problems here, please make sure you are on the latest version of Paper.
        Forks of Paper receive no support here. If you are using a fork, please make sure that this problem also affects Paper.
  - type: input
    attributes:
      label: Timings or Profile link
      description: We ask that all timings/profiles are a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: "Example: https://timings.aikar.co/?id=6b48586fbbdd48e585ca0ebb07c59dd0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
      description: If applicable, please describe your issue.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please include links to your server's config files.
      description: We need bukkit.yml, spigot.yml, paper.yml, and server.properties. Please use a paste site like https://paste.gg.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paper version.
      description: |
        Paste the full, unmodified, output of `/version` on your server WITH the Minecraft version.
        `latest` is not a version; we require the output of `/version` so we can properly track down the issue
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Please include other helpful links below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue