name: Server crash / Stacktrace
about: Report server crashes and/or scary stacktraces
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash here, please make sure you are on the latest version of Paper.
        Forks of Paper receive no support here. If you are using a fork, please make sure that this crash also happens when using Paper.

  - type: input
    attributes:
      label: Link to stack trace
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        Please use a paste site like https://paste.gg.
        Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.
      placeholder: "Example: https://paste.gg/p/anonymous/50c1b920404748b09e790130dab703e2"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: input
    attributes:
      label: Actions to reproduce (if known)
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paper version.
      description: |
        Paste the full, unmodified, output of `/version` on your server WITH the Minecraft version.
        `latest` is not a version; we require the output of `/version` so we can properly track down the issue
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please confirm the following
      options:
        - label: I am running the latest version of Paper from https://papermc.io/downloads
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this
          required: true
        - label: My version of Minecraft is supported by Paper
          required: true

  - type: markdown
    attributes:
      value: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue
