name: Paper-Test-Plugin
version: ${version}
main: io.papermc.testplugin.TestPlugin
description: Paper Test Plugin
author: PaperMC
api-version: ${apiversion}
load: STARTUP
bootstrapper: io.papermc.testplugin.TestPluginBootstrap
loader: io.papermc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
  test.plugin:
    description: Gives access to the awesome customcommand
dependencies:
  # Equal to depends: ["requiredWithBootstrap"]
  # Also checks on bootstrap
  - name: requiredWithBootstrap
    required: true
    bootstrap: true
    #
    # Equal to softdepends: ["optionalWithBootstrap"]
    # Also checks on bootstrap
  - name: optionalWithBootstrap
    bootstrap: true
    #
    # Equal to depends: ["requiredNoBootstrap"]
    # Won't check bootstrap
  - name: requiredNoBootstrap
    required: true
    #
    # Equal to softdepends: ["optionalNoBootstrap"]
    # Won't check bootstrap
  - name: optionalNoBootstrap
commands:
  customcommand:
    description: Does a really cool epic thing, nothing!
    usage: /servermode <nothing> [<also nothing>]
    permission: test.plugin
    permission-message: '<red>Now supports <bold>MINIMESSAGE</bold></red>'
